window.entities = {
  enemy: {
    class: "enemy",
    color: "red",
    buffer: null,
    volume: 50,
    panner: null,
    player: null,
    loop: null,
    wav: null,
    maxBPM: 360,
  },
  friend: {
    class: "friend",
    color: "blue",
    buffer: null,
    volume: 50,
    panner: null,
    player: null,
    loop: null,
    wav: null,
    maxBPM: 360,
  },
  obstacles: {
    class: "obstacles",
    color: "green",
    buffer: null,
    volume: 50,
    panner: null,
    player: null,
    loop: null,
    wav: null,
    maxBPM: 270,
  },
  damage: {
    class: "damage",
    color: "yellow",
    buffer: null,
    volume: 50,
    panner: null,
    player: null,
    loop: null,
    wav: null,
    maxBPM: 280,
  },
};
